stages:
  - distribute

Azure master:
  stage: distribute
  image: mcr.microsoft.com/azure-cli
  tags:
    - docker
    - amd64
  only:
    - main
  script:
    - yum update -y
    - yum install tar xz -y
    - tar cf /tmp/asab-maestro-library.tar --exclude='.git'  --exclude='./.git' --exclude='./.gitignore' --exclude='./.gitlab-ci.yml' --exclude='./README.md' --exclude='./CHANGELOG' --exclude='./CONTRIBUTING.md' --exclude='./LICENSE' .
    - xz -9 -e -T 0 /tmp/asab-maestro-library.tar
    - mv /tmp/asab-maestro-library.tar.xz asab-maestro-library.tar.xz
    # Calculate the checksum
    - sha256sum asab-maestro-library.tar.xz > asab-maestro-library.tar.xz.sha256
    
    - az storage blob upload --overwrite --file asab-maestro-library.tar.xz --container-name "\$web" --name "asab-maestro-library/asab-maestro-library-main.tar.xz" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
    - az storage blob upload --overwrite --file asab-maestro-library.tar.xz.sha256 --container-name "\$web" --name "asab-maestro-library/asab-maestro-library-main.tar.xz.sha256" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
  artifacts:
    paths:
      - asab-maestro-library.tar.xz
      - asab-maestro-library.tar.xz.sha256

Azure branch:
  stage: distribute
  image: mcr.microsoft.com/azure-cli
  tags:
    - docker
    - amd64
  only:
    - production
    - main
  script:
    - apk update
    - apk add xz
    - echo ${CI_COMMIT_BRANCH}

    - tar cf /tmp/asab-maestro-library.tar --exclude='.git'  --exclude='./.git' --exclude='./.gitignore' --exclude='./.gitlab-ci.yml' --exclude='./README.md' --exclude='./CHANGELOG' --exclude='./CONTRIBUTING.md' --exclude='./LICENSE' .
    - xz -9 -e -T 0 /tmp/asab-maestro-library.tar
    - ls /tmp
    - mv /tmp/asab-maestro-library.tar.xz asab-maestro-library-${CI_COMMIT_BRANCH}.tar.xz
    # Calculate the checksum
    - sha256sum asab-maestro-library-${CI_COMMIT_BRANCH}.tar.xz > asab-maestro-library-${CI_COMMIT_BRANCH}.tar.xz.sha256
    
    - az storage blob upload --overwrite --file asab-maestro-library-${CI_COMMIT_BRANCH}.tar.xz --container-name "\$web" --name "asab-maestro-library/asab-maestro-library-${CI_COMMIT_BRANCH}.tar.xz" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
    - az storage blob upload --overwrite --file asab-maestro-library-${CI_COMMIT_BRANCH}.tar.xz.sha256 --container-name "\$web" --name "asab-maestro-library/asab-maestro-library-${CI_COMMIT_BRANCH}.tar.xz.sha256" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"

  artifacts:
    paths:
      - asab-maestro-library-${CI_COMMIT_BRANCH}.tar.xz
      - asab-maestro-library-${CI_COMMIT_BRANCH}.tar.xz.sha256

Azure tag:
  stage: distribute
  image: mcr.microsoft.com/azure-cli

  tags:
    - docker
    - amd64

  only:
    - tags
  except:
    - branches

  script:
    - yum update -y
    - yum install tar xz -y
    - echo ${CI_COMMIT_REF_NAME}
    - tar cf /tmp/asab-maestro-library.tar --exclude='.git'  --exclude='./.git' --exclude='./.gitignore' --exclude='./.gitlab-ci.yml' --exclude='./README.md' --exclude='./CHANGELOG' --exclude='./CONTRIBUTING.md' --exclude='./LICENSE' .
    - xz -9 -e -T 0 /tmp/asab-maestro-library.tar
    - ls /tmp
    - mv /tmp/asab-maestro-library.tar.xz asab-maestro-library-${CI_COMMIT_REF_NAME}.tar.xz
    # Calculate the checksum
    - sha256sum asab-maestro-library-${CI_COMMIT_REF_NAME}.tar.xz > asab-maestro-library-${CI_COMMIT_REF_NAME}.tar.xz.sha256
    
    - az storage blob upload --overwrite --file asab-maestro-library-${CI_COMMIT_REF_NAME}.tar.xz --container-name "\$web" --name "asab-maestro-library/asab-maestro-library-${CI_COMMIT_REF_NAME}.tar.xz" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
    - az storage blob upload --overwrite --file asab-maestro-library-${CI_COMMIT_REF_NAME}.tar.xz.sha256 --container-name "\$web" --name "asab-maestro-library/asab-maestro-library-${CI_COMMIT_REF_NAME}.tar.xz.sha256" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"

  artifacts:
    paths:
      - asab-maestro-library-${CI_COMMIT_REF_NAME}.tar.xz
      - asab-maestro-library-${CI_COMMIT_REF_NAME}.tar.xz.sha256