define:
  type: rc/descriptor
  name: ASAB Config

descriptor:
  # The REST API is at tcp/8894

  image: docker.teskalabs.com/asab/asab-config

  volumes:
    # For a persistency of the configuration
    - "{{SITE}}/{{INSTANCE_ID}}/conf:/conf:ro"

  # This is critical service
  restart: always

# Other services can assign content through asab-config section in the descriptors. This sherpa uploads all content to asab-config.
sherpas:
  content:
    image: docker.teskalabs.com/asab/asab-governator:stable
    volumes:
      - "{{SITE}}/{{INSTANCE_ID}}/content:/content"
    command: python3 /content/script.py
    depends_on: ["{{INSTANCE_ID}}"]
    
files:
  - content/

asab:
  configname: conf/asab-config.conf
  config: &config {}  # specify default configuration of the service

asab-config:
  asab-config:
    __schema__:
      file: {}
    config: 
      file:
        *config  # transfer the default configuration to ASAB Config if there is no configuration set for the service, yet
      if_not_exists: true

nginx:
  api: 8894
