define:
  type: rc/descriptor
  name: ASAB Config

descriptor:
  # The REST API is at tcp/8894

  image: docker.teskalabs.com/asab/asab-config

  volumes:
    # For a persistency of the configuration
    - "{{SITE}}/{{INSTANCE_ID}}/conf:/conf:ro"

  # This is critical service
  restart: always

asab:
  configname: conf/asab-config.conf
  config: {}

api:
  private:
    port: 8894
    upstream: true

nginx:
  https:
    api:
      upstream: true
      port: 8894  # The REST API is at tcp/8893

    location /api/{{INSTANCE_ID}}:
      - {{AUTH_INTROSPECTION}}
      - {{WEBSOCKET}}
      - rewrite ^/api/{{INSTANCE_ID}}/(.*) /$1 break
      - proxy_pass http://{{NODE_ID}}:{{PORT}}

    location /api/{{SERVICE_ID}}:
      - {{AUTH_INTROSPECTION}}
      - {{WEBSOCKET}}
      - rewrite ^/api/{{SERVICE_ID}}/(.*) /$1 break
      - proxy_pass http://upstream-{{SERVICE_ID}}-{{PORT}}
