{
 "title": "Collector Overview",
 "description": "Overview of Collectors.",
 "tags": [ "LogMan.io" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "identity",
    "label": "Identity",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"identity\""
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Collector Mean EPS Overview",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_identity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "identity::tag" ], "type": "tag" }
     ],
     "measurement": "bspump.pipeline.eps",
     "query": "SELECT last(\"eps.out\") FROM \"bspump.pipeline.eps\" WHERE (\"appclass\"::tag = 'LMIOCollectorApp') AND $timeFilter GROUP BY time($__interval), \"identity\"::tag fill(null)\n",
     "select": [
      [
       { "params": [ "eps.out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIOCollectorApp" }
     ]
    }
   ]
  },
  {
   "title": "Collector EPS Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "alias": "$tag_identity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "identity::tag" ], "type": "tag" }
     ],
     "measurement": "bspump.pipeline.eps",
     "query": "SELECT last(\"eps.out\") FROM \"bspump.pipeline.eps\" WHERE (\"appclass\"::tag = 'LMIOCollectorApp') AND $timeFilter GROUP BY time($__interval), \"identity\"::tag fill(null)\n",
     "select": [
      [
       { "params": [ "eps.out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIOCollectorApp" }
     ]
    }
   ]
  },
  { "title": "Collector $identity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "identity" },
  {
   "title": "Mean EPS per Pipeline",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_pipeline",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pipeline::tag" ], "type": "tag" }
     ],
     "measurement": "bspump.pipeline.eps",
     "query": "SELECT last(\"eps.out\") FROM \"bspump.pipeline.eps\" WHERE (\"appclass\"::tag = 'LMIOCollectorApp') AND $timeFilter GROUP BY time($__interval), \"identity\"::tag fill(null)\n",
     "select": [
      [
       { "params": [ "eps.out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIOCollectorApp" },
      { "condition": "AND", "key": "identity::tag", "operator": "=~", "value": "/^$identity$/" }
     ]
    }
   ]
  },
  {
   "title": "EPS per Pipeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 10 },
   "targets": [
    {
     "alias": "$tag_pipeline",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pipeline::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bspump.pipeline.eps",
     "select": [
      [
       { "params": [ "eps.out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIOCollectorApp" },
      { "condition": "AND", "key": "identity::tag", "operator": "=~", "value": "/^$identity$/" }
     ]
    }
   ]
  },
  {
   "title": "Load1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIOCollectorApp" },
      { "condition": "AND", "key": "identity::tag", "operator": "=~", "value": "/^$identity$/" }
     ]
    }
   ]
  },
  {
   "title": "Load5",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIOCollectorApp" },
      { "condition": "AND", "key": "identity::tag", "operator": "=~", "value": "/^$identity$/" }
     ]
    }
   ]
  },
  {
   "title": "Load15",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIOCollectorApp" },
      { "condition": "AND", "key": "identity::tag", "operator": "=~", "value": "/^$identity$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Disk usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIOCollectorApp" },
      { "condition": "AND", "key": "identity::tag", "operator": "=~", "value": "/^$identity$/" }
     ]
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "logs",
     "select": [
      [
       { "params": [ "critical" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIOCollectorApp" },
      { "condition": "AND", "key": "identity::tag", "operator": "=~", "value": "/^$identity$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "logs",
     "select": [
      [
       { "params": [ "errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIOCollectorApp" },
      { "condition": "AND", "key": "identity::tag", "operator": "=~", "value": "/^$identity$/" }
     ]
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "logs",
     "select": [
      [
       { "params": [ "warnings" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIOCollectorApp" },
      { "condition": "AND", "key": "identity::tag", "operator": "=~", "value": "/^$identity$/" }
     ]
    }
   ]
  }
 ]
}