{
 "title": "Event Lane Detail",
 "tags": [ "LogMan.io" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant",
    "query": "SHOW TAG VALUES FROM \"lmio.eventlane.event\" WITH KEY = \"tenant\""
   },
   {
    "name": "instances",
    "query": "show tag values from  \"bspump.pipeline.dutycycle\"  with key=\"instance_id\"  WHERE value =~ /lmio-parsec-$tenant-${eventlane:text}.*/ "
   },
   {
    "name": "eventlane",
    "query": "SHOW TAG VALUES FROM \"lmio.eventlane.event\" WITH KEY = \"eventlane\" WHERE \"tenant\" =~ /^$tenant$/"
   }
  ]
 },
 "panels": [
  { "title": "Event Lane Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "EPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "instance_id::tag" ], "type": "tag" }
     ],
     "measurement": "lmio.eventlane.event",
     "select": [
      [
       { "params": [ "event.out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "tenant::tag", "operator": "=~", "value": "/^$tenant$/" },
      { "condition": "AND", "key": "eventlane::tag", "operator": "=~", "value": "/^$eventlane$/" },
      { "condition": "AND", "key": "appclass::tag", "operator": "=", "value": "LMIOParsecApplication" }
     ]
    }
   ]
  },
  {
   "title": "Parsed events in Elasticsearch",
   "type": "stat",
   "description": "Total number of parsed events for this event lane stored in Elasticsearch.",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices_stats_total",
     "select": [
      [
       { "params": [ "docs_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "index_name::tag",
       "operator": "=~",
       "value": "/^.*lmio-${tenant}-events-${eventlane:text}.*/"
      }
     ]
    }
   ]
  },
  {
   "title": "Unparsed events in Elasticsearch",
   "type": "stat",
   "description": "Total number of unparsed events for this event lane stored in Elasticsearch.",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices_stats_total",
     "select": [
      [
       { "params": [ "docs_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "index_name::tag", "operator": "=~", "value": "/lmio-$tenant-others/" }
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch Storage Size",
   "type": "stat",
   "description": "Size of all Elasticsearch event lane indices.",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices_stats_total",
     "select": [
      [
       { "params": [ "store_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "condition": "AND",
       "key": "index_name::tag",
       "operator": "=~",
       "value": "/^lmio-$tenant-events-${eventlane:text}.*$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Number of parsecs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_status",
     "query": "SELECT count(\"container_id\") FROM \"docker_container_status\" WHERE (\"instance_id\"::tag =~ /^lmio-parsec-${tenant}-${eventlane:text}.*/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "container_id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      {
       "key": "instance_id::tag",
       "operator": "=~",
       "value": "/^lmio-parsec-${tenant}-${eventlane:text}.*/"
      }
     ]
    }
   ]
  },
  { "title": "LMIO Receiver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "EVENTS IN",
   "type": "timeseries",
   "description": "Number of incoming events.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "[[tag_instance_id]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance_id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "commlink",
     "select": [
      [
       { "params": [ "event.in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tenant::tag", "operator": "=~", "value": "/^$tenant$/" },
      { "condition": "AND", "key": "stream::tag", "operator": "=~", "value": "/${eventlane:text}.*/" }
     ]
    }
   ]
  },
  {
   "title": "BYTES IN",
   "type": "timeseries",
   "description": "Size of incoming events in bytes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "[[tag_instance_id]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance_id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "commlink",
     "select": [
      [
       { "params": [ "bytes.in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tenant::tag", "operator": "=~", "value": "/^$tenant$/" },
      { "condition": "AND", "key": "stream::tag", "operator": "=~", "value": "/^${eventlane:text}/" }
     ]
    }
   ]
  },
  { "title": "LMIO Parsec", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "EPS OUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "alias": "[[tag_instance_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lmio.eventlane.event",
     "select": [
      [
       { "params": [ "event.out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "tenant::tag", "operator": "=~", "value": "/^$tenant$/" },
      { "condition": "AND", "key": "eventlane::tag", "operator": "=~", "value": "/^$eventlane$/" },
      { "condition": "AND", "key": "appclass::tag", "operator": "=", "value": "LMIOParsecApplication" }
     ]
    }
   ]
  },
  {
   "title": "EPS DROP",
   "type": "timeseries",
   "description": "Number of events that were not parsed per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "alias": "[[tag_instance_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lmio.eventlane.event",
     "select": [
      [
       { "params": [ "event.drop" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tenant::tag", "operator": "=~", "value": "/^$tenant$/" },
      { "condition": "AND", "key": "eventlane::tag", "operator": "=~", "value": "/^$eventlane$/" },
      { "condition": "AND", "key": "appclass::tag", "operator": "=", "value": "LMIOParsecApplication" }
     ]
    }
   ]
  },
  {
   "title": "Total Lag on RECEIVED topic per partition",
   "type": "timeseries",
   "description": "Number of non-consumed messages on RECEIVED topic per partition.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "Partition $tag_partition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "partition::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "burrow_partition",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=~",
       "value": "/received.$tenant.${eventlane:text}.*/"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages Per Minute Per Partition",
   "type": "timeseries",
   "description": "Number of incoming messages to EVENTS topic per partition.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "alias": "Partition $tag_partition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "partition::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "burrow_topic",
     "select": [
      [
       { "params": [ "offset" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=~",
       "value": "/events.$tenant.${eventlane:text}.*/"
      }
     ]
    }
   ]
  },
  { "title": "LMIO Depositor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "EPS OUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "alias": "[[tag_instance_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lmio.eventlane.event",
     "select": [
      [
       { "params": [ "event.out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "tenant::tag", "operator": "=~", "value": "/^$tenant$/" },
      { "condition": "AND", "key": "eventlane::tag", "operator": "=~", "value": "/^$eventlane$/" },
      { "condition": "AND", "key": "appclass::tag", "operator": "=", "value": "LMIODepositorApplication" }
     ]
    }
   ]
  },
  {
   "title": "EPS DROP",
   "type": "timeseries",
   "description": "Number of events that were not parsed per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "alias": "[[tag_instance_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lmio.eventlane.event",
     "select": [
      [
       { "params": [ "event.drop" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tenant::tag", "operator": "=~", "value": "/^$tenant$/" },
      { "condition": "AND", "key": "eventlane::tag", "operator": "=~", "value": "/^$eventlane$/" },
      { "condition": "AND", "key": "appclass::tag", "operator": "=", "value": "LMIODepositorApplication" }
     ]
    }
   ]
  },
  {
   "title": "Detail of $instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "instances",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "timeseries",
     "description": "Memory usage of instance: $instances",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "Memory usage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "select": [
        [
         { "params": [ "usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        {
         "key": "instance_id::tag",
         "operator": "=~",
         "value": "/lmio-parsec-$tenant-${eventlane:text}.*/"
        }
       ]
      }
     ]
    },
    {
     "title": "Duty Cycle",
     "type": "timeseries",
     "description": "Duty Cycle of instance: $instances",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "alias": "Duty Cycle",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "bspump.pipeline.dutycycle",
       "select": [
        [
         { "params": [ "ready" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        {
         "key": "instance_id::tag",
         "operator": "=~",
         "value": "/lmio-parsec-$tenant-${eventlane:text}.*/"
        }
       ]
      }
     ]
    }
   ]
  }
 ]
}