{
 "title": "Kafka Lag Detail",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "consumerGroup",
    "query": "show tag values from \"burrow_group\" with key = \"group\""
   },
   {
    "name": "topic",
    "query": "show tag values from \"burrow_partition\" with key=\"topic\" where \"group\"='$consumerGroup'"
   },
   {
    "name": "partition",
    "query": "show tag values from \"burrow_partition\" with key=\"partition\" where \"group\"='$consumerGroup' and topic='$topic'"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Group Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "burrow_group",
     "select": [
      [
       { "params": [ "status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$consumerGroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Group Total Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TotalLag",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "burrow_group",
     "select": [
      [
       { "params": [ "total_lag" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$consumerGroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Partition Max lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Maxlag",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "burrow_group",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$consumerGroup$/" }
     ]
    }
   ]
  },
  {
   "title": "$topic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Partition Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "burrow_partition",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$consumerGroup$/" },
      { "condition": "AND", "key": "topic", "operator": "=~", "value": "/^$topic$/" }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages Per Minute Per Partition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "burrow_topic",
     "select": [
      [
       { "params": [ "offset" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=~", "value": "/^$topic$/" }
     ]
    }
   ]
  }
 ]
}