{
 "title": "LogMan.io Alerts",
 "tags": [ "LogMan.io" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Number of Consumed Signals",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "signal.in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "signals_consumed",
     "select": [
      [
       { "params": [ "signal.in" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "signal.in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LmioAlertApplication" }
     ]
    }
   ]
  },
  {
   "title": "Total Number of Unprocessed Signals",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "signal.drop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "signals_unprocessed",
     "select": [
      [
       { "params": [ "signal.drop" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "signal.drop" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LmioAlertApplication" }
     ]
    }
   ]
  },
  {
   "title": "Total Number of Severe Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "critical",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "logs",
     "select": [
      [
       { "params": [ "critical" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "critical" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LmioAlertApplication" }
     ]
    },
    {
     "alias": "errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "logs",
     "select": [
      [
       { "params": [ "errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LmioAlertApplication" }
     ]
    },
    {
     "alias": "warnings",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "logs",
     "select": [
      [
       { "params": [ "warnings" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "warnings" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LmioAlertApplication" }
     ]
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Severe Logs Overview",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "logs",
     "select": [
      [
       { "params": [ "warnings" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "warning" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LmioAlertApplication" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "logs",
     "select": [
      [
       { "params": [ "errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "error" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LmioAlertApplication" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "logs",
     "select": [
      [
       { "params": [ "critical" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "critical" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LmioAlertApplication" }
     ]
    }
   ]
  },
  {
   "title": "Kafka Lag on lmio-signals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "lag.last",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kafka.consumer_group",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "lag.last" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "group::tag", "operator": "=", "value": "lmio-alerts" },
      { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "lmio-signals" }
     ]
    }
   ]
  },
  {
   "title": "Consumed Signals",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "signal.in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "signals_consumed",
     "select": [
      [
       { "params": [ "signal.in" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "signal.in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LmioAlertApplication" }
     ]
    }
   ]
  },
  {
   "title": "Unprocessed Signals",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "signal.drop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "signals_unprocessed",
     "select": [
      [
       { "params": [ "signal.drop" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "signal.drop" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LmioAlertApplication" }
     ]
    }
   ]
  }
 ]
}