{
 "title": "LogMan.io Depositor",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Failed Bulks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch.insert",
     "select": [
      [
       { "params": [ "fail" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Queue Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch.outputqueue",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duty Cycle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bspump.pipeline.dutycycle",
     "select": [
      [
       { "params": [ "ready" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIODepositorApplication" }
     ]
    }
   ]
  },
  {
   "title": "EPS IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bspump.pipeline.eps",
     "select": [
      [
       { "params": [ "eps.in" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIODepositorApplication" }
     ]
    }
   ]
  },
  {
   "title": "EPS OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bspump.pipeline.eps",
     "select": [
      [
       { "params": [ "eps.out" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIODepositorApplication" }
     ]
    }
   ]
  },
  {
   "title": "Output Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch.outputqueue",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIODepositorApplication" }
     ]
    }
   ]
  },
  {
   "title": "Duty Cycle",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bspump.pipeline.dutycycle",
     "select": [
      [
       { "params": [ "ready" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Duty Cycle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIODepositorApplication" }
     ]
    }
   ]
  },
  {
   "title": "Throughput IN",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bspump.pipeline.eps",
     "select": [
      [
       { "params": [ "eps.in" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eps.in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIODepositorApplication" }
     ]
    }
   ]
  },
  {
   "title": "Throughput OUT",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bspump.pipeline.eps",
     "select": [
      [
       { "params": [ "eps.out" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eps.out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIODepositorApplication" }
     ]
    }
   ]
  },
  {
   "title": "Successful BULK inserts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 39 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch.insert",
     "select": [
      [
       { "params": [ "ok" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Ok" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIODepositorApplication" }
     ]
    }
   ]
  },
  {
   "title": "Failed BULK Inserts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 39 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch.insert",
     "select": [
      [
       { "params": [ "fail" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Failed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "appclass::tag", "operator": "=", "value": "LMIODepositorApplication" }
     ]
    }
   ]
  }
 ]
}