{
 "title": "LogMan.io Pipeline Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": "SHOW TAG VALUES WITH KEY = \"pipeline\""
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": "SHOW TAG VALUES WITH KEY = \"tenant\""
   }
  ]
 },
 "panels": [
  {
   "title": "$pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "pipeline",
   "targets": [
    {}
   ]
  },
  {
   "title": "Event In/Out in $pipeline for $tenant",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "bspump.pipeline.eps",
     "select": [
      [
       { "params": [ "eps.in" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "event.in" ], "type": "alias" }
      ],
      [
       { "params": [ "eps.out" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "event.out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=~", "value": "/^$pipeline$/" }
     ]
    }
   ]
  },
  {
   "title": "Duty Cycles in $pipeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "bspump.pipeline.dutycycle",
     "select": [
      [
       { "params": [ "ready" ], "type": "field" },
       { "params": [ "Duty Cycle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=~", "value": "/^$pipeline$/" }
     ]
    }
   ]
  },
  {
   "title": "Time Drift in $pipeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "timedrift",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=~", "value": "/^$pipeline$/" }
     ]
    }
   ]
  }
 ]
}