{
 "title": "System-level Overview",
 "tags": [ "system" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node_id",
    "label": "Node",
    "query": "SHOW TAG VALUES WITH KEY = \"node_id\""
   }
  ]
 },
 "panels": [
  { "title": "$node_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node_id" },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "idle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_path",
     "groupBy": [
      { "params": [ "path::tag" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT (last(\"used\") / last(\"total\")) * 100 FROM \"disk\" WHERE (\"node_id\"::tag =~ /^$node_id$/) AND $timeFilter GROUP BY \"path\"::tag fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" },
      { "condition": "AND", "key": "path::tag", "operator": "!~", "value": "/^\\.\\/.*$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage IO",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 300" ], "type": "math" },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 300" ], "type": "math" },
       { "params": [ "write" ], "type": "alias" }
      ],
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 300" ], "type": "math" },
       { "params": [ "read IO" ], "type": "alias" }
      ],
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 300" ], "type": "math" },
       { "params": [ "write IO" ], "type": "alias" }
      ],
      [
       { "params": [ "iops_in_progress" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Network in",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Network out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap in",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap out",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Process count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  },
  {
   "title": "I/O wait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Zombie count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=~", "value": "/^$node_id$/" }
     ]
    }
   ]
  }
 ]
}